### ISSUE TITLE
code for electra model

### ISSUE THREAD

**Issue by chijames** [DeepLearnXMU/Structure-Self-Aware#1]
Hi,

Is it possible to also release the electra training code? Many thanks!

**Comment by Soistesimmer** [comment]
> Hi,
> 
> Is it possible to also release the electra training code? Many thanks!

Thank you for your attention. We just use the open-source tool from https://huggingface.co/transformers/model_doc/electra.html. You only need to tokenize the corpus with ELECTRA tokenizer, and substitute the token-level HGRU with ELECTRA-small model. We didn't change any other settings.
